(define (batch-matthew pattern)  
	(let* ((filelist (cadr (file-glob pattern 1))))  
		(while (not (null? filelist))  
			(let* (
					(filename (car filelist))  
					(image (car (gimp-file-load RUN-NONINTERACTIVE filename filename)))  
					(drawable (car (gimp-image-get-active-layer image)))
					(layer (car (gimp-layer-copy drawable TRUE)))
					(newName (string-append "./batched/" (car (gimp-image-get-name image))))
				)
				(gimp-levels-stretch drawable)
				(plug-in-unsharp-mask RUN-NONINTERACTIVE image drawable 5 0.4 0)
				(gimp-image-add-layer image layer -1)
				(plug-in-color-enhance RUN-NONINTERACTIVE image layer) 
				(gimp-layer-set-opacity layer 05)
				(gimp-image-flatten image)
				(set! drawable (car (gimp-image-get-active-layer image)))
				(gimp-file-save RUN-NONINTERACTIVE image drawable newName newName)  
				(gimp-image-delete image)
			)  
			(set! filelist (cdr filelist))
		)
	)
)